.TH "_cookbook._doctest" 3 "Wed Sep 17 2014" "Version 0.0.0" "admin-linux" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_cookbook._doctest \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBfunc_1\fP"
.br
.ti -1c
.RI "def \fBfunc_2\fP"
.br
.ti -1c
.RI "def \fBfunc_3\fP"
.br
.ti -1c
.RI "def \fBfunc_4\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def _cookbook\&._doctest\&.func_1 ()"

.PP
.nf
No return.

>>> func_1()
.fi
.PP
 
.PP
Definition at line 39 of file _doctest\&.py\&.
.SS "def _cookbook\&._doctest\&.func_2 ()"

.PP
.nf
Print a blank line.

>>> func_2()
<BLANKLINE>
.fi
.PP
 
.PP
Definition at line 48 of file _doctest\&.py\&.
.SS "def _cookbook\&._doctest\&.func_3 (msg)"

.PP
.nf
Print a string.

@param msg -- A message to be printed out

>>> func_3("Hello")
Hello
.fi
.PP
 
.PP
Definition at line 58 of file _doctest\&.py\&.
.SS "def _cookbook\&._doctest\&.func_4 ()"

.PP
.nf
Raise an exception (ValueError).

@exception ValueError

>>> func_4()
Traceback (most recent call last):
    ...
ValueError: error description

.fi
.PP
 
.PP
Definition at line 70 of file _doctest\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for admin-linux from the source code\&.
